// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/potatosoft/protobuf/packet.proto

package com.potatosoft.protobuf;

public final class PacketProtos {
  private PacketProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PacketOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 version = 1;
    /**
     * <code>required int32 version = 1;</code>
     *
     * <pre>
     *
     * Define version and messageType as int32, it was originally byte and short.
     * It is a 'variant' type variable that will change size depending on the data that is stored in it.
     * </pre>
     */
    boolean hasVersion();
    /**
     * <code>required int32 version = 1;</code>
     *
     * <pre>
     *
     * Define version and messageType as int32, it was originally byte and short.
     * It is a 'variant' type variable that will change size depending on the data that is stored in it.
     * </pre>
     */
    int getVersion();

    // required .com.potatosoft.protobuf.Packet.MessageType messageType = 2;
    /**
     * <code>required .com.potatosoft.protobuf.Packet.MessageType messageType = 2;</code>
     */
    boolean hasMessageType();
    /**
     * <code>required .com.potatosoft.protobuf.Packet.MessageType messageType = 2;</code>
     */
    com.potatosoft.protobuf.PacketProtos.Packet.MessageType getMessageType();

    // required int32 userId = 3;
    /**
     * <code>required int32 userId = 3;</code>
     */
    boolean hasUserId();
    /**
     * <code>required int32 userId = 3;</code>
     */
    int getUserId();

    // required string payload = 4;
    /**
     * <code>required string payload = 4;</code>
     */
    boolean hasPayload();
    /**
     * <code>required string payload = 4;</code>
     */
    java.lang.String getPayload();
    /**
     * <code>required string payload = 4;</code>
     */
    com.google.protobuf.ByteString
        getPayloadBytes();
  }
  /**
   * Protobuf type {@code com.potatosoft.protobuf.Packet}
   */
  public static final class Packet extends
      com.google.protobuf.GeneratedMessage
      implements PacketOrBuilder {
    // Use Packet.newBuilder() to construct.
    private Packet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Packet(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Packet defaultInstance;
    public static Packet getDefaultInstance() {
      return defaultInstance;
    }

    public Packet getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Packet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.potatosoft.protobuf.PacketProtos.Packet.MessageType value = com.potatosoft.protobuf.PacketProtos.Packet.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                messageType_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              userId_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              payload_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.potatosoft.protobuf.PacketProtos.internal_static_com_potatosoft_protobuf_Packet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.potatosoft.protobuf.PacketProtos.internal_static_com_potatosoft_protobuf_Packet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.potatosoft.protobuf.PacketProtos.Packet.class, com.potatosoft.protobuf.PacketProtos.Packet.Builder.class);
    }

    public static com.google.protobuf.Parser<Packet> PARSER =
        new com.google.protobuf.AbstractParser<Packet>() {
      public Packet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Packet(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Packet> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.potatosoft.protobuf.Packet.MessageType}
     *
     * <pre>
     * enum values use variant encoding on the wire, so negative values are not inefficient
     * and not recommended.
     * Also, value should be in the range of a 32-bit integer.
     * https://developers.google.com/protocol-buffers/docs/proto
     * Add any enum type you want to use.
     * </pre>
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>LOGIN = 0;</code>
       */
      LOGIN(0, 0),
      /**
       * <code>LOGOUT = 1;</code>
       */
      LOGOUT(1, 1),
      /**
       * <code>GAMEPLAY = 2;</code>
       */
      GAMEPLAY(2, 2),
      /**
       * <code>CHAT = 3;</code>
       */
      CHAT(3, 3),
      /**
       * <code>PURCHASE = 4;</code>
       */
      PURCHASE(4, 4),
      ;

      /**
       * <code>LOGIN = 0;</code>
       */
      public static final int LOGIN_VALUE = 0;
      /**
       * <code>LOGOUT = 1;</code>
       */
      public static final int LOGOUT_VALUE = 1;
      /**
       * <code>GAMEPLAY = 2;</code>
       */
      public static final int GAMEPLAY_VALUE = 2;
      /**
       * <code>CHAT = 3;</code>
       */
      public static final int CHAT_VALUE = 3;
      /**
       * <code>PURCHASE = 4;</code>
       */
      public static final int PURCHASE_VALUE = 4;


      public final int getNumber() { return value; }

      public static MessageType valueOf(int value) {
        switch (value) {
          case 0: return LOGIN;
          case 1: return LOGOUT;
          case 2: return GAMEPLAY;
          case 3: return CHAT;
          case 4: return PURCHASE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.potatosoft.protobuf.PacketProtos.Packet.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.potatosoft.protobuf.Packet.MessageType)
    }

    private int bitField0_;
    // required int32 version = 1;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required int32 version = 1;</code>
     *
     * <pre>
     *
     * Define version and messageType as int32, it was originally byte and short.
     * It is a 'variant' type variable that will change size depending on the data that is stored in it.
     * </pre>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 version = 1;</code>
     *
     * <pre>
     *
     * Define version and messageType as int32, it was originally byte and short.
     * It is a 'variant' type variable that will change size depending on the data that is stored in it.
     * </pre>
     */
    public int getVersion() {
      return version_;
    }

    // required .com.potatosoft.protobuf.Packet.MessageType messageType = 2;
    public static final int MESSAGETYPE_FIELD_NUMBER = 2;
    private com.potatosoft.protobuf.PacketProtos.Packet.MessageType messageType_;
    /**
     * <code>required .com.potatosoft.protobuf.Packet.MessageType messageType = 2;</code>
     */
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .com.potatosoft.protobuf.Packet.MessageType messageType = 2;</code>
     */
    public com.potatosoft.protobuf.PacketProtos.Packet.MessageType getMessageType() {
      return messageType_;
    }

    // required int32 userId = 3;
    public static final int USERID_FIELD_NUMBER = 3;
    private int userId_;
    /**
     * <code>required int32 userId = 3;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 userId = 3;</code>
     */
    public int getUserId() {
      return userId_;
    }

    // required string payload = 4;
    public static final int PAYLOAD_FIELD_NUMBER = 4;
    private java.lang.Object payload_;
    /**
     * <code>required string payload = 4;</code>
     */
    public boolean hasPayload() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string payload = 4;</code>
     */
    public java.lang.String getPayload() {
      java.lang.Object ref = payload_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          payload_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string payload = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPayloadBytes() {
      java.lang.Object ref = payload_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        payload_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      version_ = 0;
      messageType_ = com.potatosoft.protobuf.PacketProtos.Packet.MessageType.LOGIN;
      userId_ = 0;
      payload_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMessageType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPayload()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, messageType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, userId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getPayloadBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, messageType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, userId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getPayloadBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.potatosoft.protobuf.PacketProtos.Packet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.potatosoft.protobuf.PacketProtos.Packet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.potatosoft.protobuf.PacketProtos.Packet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.potatosoft.protobuf.PacketProtos.Packet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.potatosoft.protobuf.PacketProtos.Packet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.potatosoft.protobuf.PacketProtos.Packet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.potatosoft.protobuf.PacketProtos.Packet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.potatosoft.protobuf.PacketProtos.Packet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.potatosoft.protobuf.PacketProtos.Packet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.potatosoft.protobuf.PacketProtos.Packet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.potatosoft.protobuf.PacketProtos.Packet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.potatosoft.protobuf.Packet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.potatosoft.protobuf.PacketProtos.PacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.potatosoft.protobuf.PacketProtos.internal_static_com_potatosoft_protobuf_Packet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.potatosoft.protobuf.PacketProtos.internal_static_com_potatosoft_protobuf_Packet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.potatosoft.protobuf.PacketProtos.Packet.class, com.potatosoft.protobuf.PacketProtos.Packet.Builder.class);
      }

      // Construct using com.potatosoft.protobuf.PacketProtos.Packet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        messageType_ = com.potatosoft.protobuf.PacketProtos.Packet.MessageType.LOGIN;
        bitField0_ = (bitField0_ & ~0x00000002);
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        payload_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.potatosoft.protobuf.PacketProtos.internal_static_com_potatosoft_protobuf_Packet_descriptor;
      }

      public com.potatosoft.protobuf.PacketProtos.Packet getDefaultInstanceForType() {
        return com.potatosoft.protobuf.PacketProtos.Packet.getDefaultInstance();
      }

      public com.potatosoft.protobuf.PacketProtos.Packet build() {
        com.potatosoft.protobuf.PacketProtos.Packet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.potatosoft.protobuf.PacketProtos.Packet buildPartial() {
        com.potatosoft.protobuf.PacketProtos.Packet result = new com.potatosoft.protobuf.PacketProtos.Packet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.messageType_ = messageType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.payload_ = payload_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.potatosoft.protobuf.PacketProtos.Packet) {
          return mergeFrom((com.potatosoft.protobuf.PacketProtos.Packet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.potatosoft.protobuf.PacketProtos.Packet other) {
        if (other == com.potatosoft.protobuf.PacketProtos.Packet.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasPayload()) {
          bitField0_ |= 0x00000008;
          payload_ = other.payload_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          
          return false;
        }
        if (!hasMessageType()) {
          
          return false;
        }
        if (!hasUserId()) {
          
          return false;
        }
        if (!hasPayload()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.potatosoft.protobuf.PacketProtos.Packet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.potatosoft.protobuf.PacketProtos.Packet) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 version = 1;
      private int version_ ;
      /**
       * <code>required int32 version = 1;</code>
       *
       * <pre>
       *
       * Define version and messageType as int32, it was originally byte and short.
       * It is a 'variant' type variable that will change size depending on the data that is stored in it.
       * </pre>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 version = 1;</code>
       *
       * <pre>
       *
       * Define version and messageType as int32, it was originally byte and short.
       * It is a 'variant' type variable that will change size depending on the data that is stored in it.
       * </pre>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>required int32 version = 1;</code>
       *
       * <pre>
       *
       * Define version and messageType as int32, it was originally byte and short.
       * It is a 'variant' type variable that will change size depending on the data that is stored in it.
       * </pre>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 version = 1;</code>
       *
       * <pre>
       *
       * Define version and messageType as int32, it was originally byte and short.
       * It is a 'variant' type variable that will change size depending on the data that is stored in it.
       * </pre>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }

      // required .com.potatosoft.protobuf.Packet.MessageType messageType = 2;
      private com.potatosoft.protobuf.PacketProtos.Packet.MessageType messageType_ = com.potatosoft.protobuf.PacketProtos.Packet.MessageType.LOGIN;
      /**
       * <code>required .com.potatosoft.protobuf.Packet.MessageType messageType = 2;</code>
       */
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .com.potatosoft.protobuf.Packet.MessageType messageType = 2;</code>
       */
      public com.potatosoft.protobuf.PacketProtos.Packet.MessageType getMessageType() {
        return messageType_;
      }
      /**
       * <code>required .com.potatosoft.protobuf.Packet.MessageType messageType = 2;</code>
       */
      public Builder setMessageType(com.potatosoft.protobuf.PacketProtos.Packet.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.potatosoft.protobuf.Packet.MessageType messageType = 2;</code>
       */
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        messageType_ = com.potatosoft.protobuf.PacketProtos.Packet.MessageType.LOGIN;
        onChanged();
        return this;
      }

      // required int32 userId = 3;
      private int userId_ ;
      /**
       * <code>required int32 userId = 3;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 userId = 3;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>required int32 userId = 3;</code>
       */
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000004;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 userId = 3;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        userId_ = 0;
        onChanged();
        return this;
      }

      // required string payload = 4;
      private java.lang.Object payload_ = "";
      /**
       * <code>required string payload = 4;</code>
       */
      public boolean hasPayload() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string payload = 4;</code>
       */
      public java.lang.String getPayload() {
        java.lang.Object ref = payload_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          payload_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string payload = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPayloadBytes() {
        java.lang.Object ref = payload_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          payload_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string payload = 4;</code>
       */
      public Builder setPayload(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string payload = 4;</code>
       */
      public Builder clearPayload() {
        bitField0_ = (bitField0_ & ~0x00000008);
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      /**
       * <code>required string payload = 4;</code>
       */
      public Builder setPayloadBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        payload_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.potatosoft.protobuf.Packet)
    }

    static {
      defaultInstance = new Packet(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.potatosoft.protobuf.Packet)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_potatosoft_protobuf_Packet_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_potatosoft_protobuf_Packet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n2src/main/java/com/potatosoft/protobuf/" +
      "packet.proto\022\027com.potatosoft.protobuf\"\310\001" +
      "\n\006Packet\022\017\n\007version\030\001 \002(\005\022@\n\013messageType" +
      "\030\002 \002(\0162+.com.potatosoft.protobuf.Packet." +
      "MessageType\022\016\n\006userId\030\003 \002(\005\022\017\n\007payload\030\004" +
      " \002(\t\"J\n\013MessageType\022\t\n\005LOGIN\020\000\022\n\n\006LOGOUT" +
      "\020\001\022\014\n\010GAMEPLAY\020\002\022\010\n\004CHAT\020\003\022\014\n\010PURCHASE\020\004" +
      "B\'\n\027com.potatosoft.protobufB\014PacketProto" +
      "s"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_potatosoft_protobuf_Packet_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_potatosoft_protobuf_Packet_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_potatosoft_protobuf_Packet_descriptor,
              new java.lang.String[] { "Version", "MessageType", "UserId", "Payload", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
